name: Generate Ninja Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: PhanikiranNK

          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_limit: 6

          plugin_stars: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed

          output_action: github-pages
          output_branch: output
          output_filename: github-metrics.svg
